[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = "1.0.214"
serde_json = "1.0.132"
miette = { version = "7.2.0", features = ["fancy-no-syscall", "supports-color", "supports-unicode"] }